// Portfolio Projects Database
const projectsData = [
  {
    id: 1,
    title: "Loja Virtual Premium",
    client: "TechStyle Fashion",
    category: "ecommerce",
    year: 2026,
    technologies: ["react", "node", "stripe"],
    image: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    icon: "🛍️",
    shortDescription: "E-commerce completo com gestão avançada de produtos e múltiplos gateways de pagamento.",
    fullDescription: "Desenvolvemos uma plataforma de e-commerce de alta performance para a TechStyle Fashion, integrando gestão completa de produtos, múltiplos gateways de pagamento e um sistema de analytics em tempo real.",
    challenge: "A TechStyle precisava de uma solução que suportasse alto volume de transações simultâneas, integrasse com seu ERP legado e oferecesse uma experiência de compra fluida em todos os dispositivos.",
    solution: "Criamos uma arquitetura escalável usando React no frontend para uma interface responsiva e dinâmica, Node.js no backend para processar transações de forma eficiente, e integramos múltiplos gateways de pagamento incluindo Stripe e PagSeguro.",
    results: [
      "Aumento de 150% nas conversões online",
      "Redução de 40% no tempo de checkout",
      "99.9% de uptime desde o lançamento",
      "Integração com 3 gateways de pagamento",
      "Sistema de recomendação inteligente implementado"
    ],
    techStack: ["React", "Node.js", "MongoDB", "Stripe", "Redis", "AWS"],
    duration: "4 meses",
    team: "6 desenvolvedores",
    link: "#"
  },
  {
    id: 2,
    title: "Sistema de Gestão Médica",
    client: "InovaMed Clínicas",
    category: "system",
    year: 2025,
    technologies: ["vue", "laravel"],
    image: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    icon: "🏥",
    shortDescription: "Plataforma completa de gestão clínica com prontuários eletrônicos e agendamento inteligente.",
    fullDescription: "Sistema completo de gestão para clínicas médicas, incluindo prontuário eletrônico, agendamento online, controle financeiro, e integração com laboratórios e operadoras de saúde.",
    challenge: "A InovaMed gerenciava 3 clínicas com sistemas diferentes, causando inconsistência de dados e dificuldade no controle financeiro. Precisavam centralizar todas as operações mantendo conformidade com LGPD e normas do CFM.",
    solution: "Desenvolvemos uma solução web centralizada usando Vue.js para interface responsiva e Laravel para backend robusto. Implementamos criptografia de ponta a ponta para dados sensíveis e auditoria completa de acessos.",
    results: [
      "Centralização de 3 clínicas em uma única plataforma",
      "Redução de 60% no tempo de agendamento",
      "100% de conformidade com LGPD",
      "Diminuição de 45% em erros de prontuário",
      "Integração com 5 laboratórios parceiros"
    ],
    techStack: ["Vue.js", "Laravel", "MySQL", "Redis", "Docker"],
    duration: "6 meses",
    team: "8 desenvolvedores",
    link: "#"
  },
  {
    id: 3,
    title: "App de Delivery Inteligente",
    client: "QuickBite Foods",
    category: "mobile",
    year: 2026,
    technologies: ["react-native", "node"],
    image: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    icon: "📲",
    shortDescription: "Aplicativo de delivery com rastreamento em tempo real e programa de fidelidade.",
    fullDescription: "Aplicativo mobile completo para delivery de comida, com rastreamento em tempo real, múltiplas formas de pagamento, sistema de avaliações e programa de fidelidade gamificado.",
    challenge: "O QuickBite queria competir com grandes players do mercado oferecendo uma experiência superior e taxas menores para restaurantes parceiros.",
    solution: "Desenvolvemos apps nativos para iOS e Android usando React Native, integração com Google Maps para rastreamento, sistema de pagamento in-app, e um algoritmo de matching inteligente entre entregadores e pedidos.",
    results: [
      "50.000+ downloads nos primeiros 3 meses",
      "Rating médio de 4.8 estrelas",
      "Tempo médio de entrega: 28 minutos",
      "200+ restaurantes parceiros",
      "Sistema de fidelidade aumentou pedidos recorrentes em 85%"
    ],
    techStack: ["React Native", "Node.js", "PostgreSQL", "Redis", "Google Maps API", "Firebase"],
    duration: "5 meses",
    team: "7 desenvolvedores",
    link: "#"
  },
  {
    id: 4,
    title: "Portfólio Criativo Interativo",
    client: "Pixel Perfect Design",
    category: "web",
    year: 2025,
    technologies: ["react"],
    image: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
    icon: "🎨",
    shortDescription: "Website institucional com animações interativas e galeria de projetos dinâmica.",
    fullDescription: "Website institucional para agência de design com foco em experiência visual impressionante, animações suaves, galeria interativa de projetos e sistema de blog integrado.",
    challenge: "A Pixel Perfect queria um site que refletisse sua criatividade e expertise em design, com animações complexas mas mantendo performance excelente.",
    solution: "Utilizamos Next.js para SSR e otimização SEO, GSAP para animações fluidas, e Sanity CMS headless para gerenciamento de conteúdo. Implementamos lazy loading e code splitting para manter o site rápido.",
    results: [
      "Score 98/100 no Google PageSpeed",
      "Aumento de 220% no tempo de permanência",
      "Redução de 35% na taxa de rejeição",
      "10+ prêmios de design web",
      "Aumento de 180% em leads qualificados"
    ],
    techStack: ["Next.js", "GSAP", "Sanity CMS", "Tailwind CSS", "Vercel"],
    duration: "3 meses",
    team: "4 desenvolvedores",
    link: "#"
  },
  {
    id: 5,
    title: "Dashboard de Analytics Avançado",
    client: "DataDrive Solutions",
    category: "system",
    year: 2026,
    technologies: ["angular", "node"],
    image: "linear-gradient(135deg, #30cfd0 0%, #330867 100%)",
    icon: "📊",
    shortDescription: "Dashboard completo de análise de dados com visualizações interativas.",
    fullDescription: "Sistema de analytics empresarial com visualizações interativas, relatórios personalizados, integração com múltiplas fontes de dados e alertas automatizados.",
    challenge: "A DataDrive precisava consolidar dados de 15+ fontes diferentes (Google Analytics, CRM, ERP, redes sociais) em uma única visualização coerente e em tempo real.",
    solution: "Construímos uma arquitetura de microserviços com Angular no frontend para dashboards dinâmicos, Node.js para APIs de integração, e PostgreSQL com TimescaleDB para séries temporais. Implementamos cache com Redis e processamento em background com Bull Queue.",
    results: [
      "Consolidação de 15 fontes de dados",
      "Atualização de métricas em tempo real (< 2s)",
      "Criação de 50+ relatórios customizados",
      "Economia de 120 horas/mês em análise manual",
      "Alertas automatizados para 30+ KPIs"
    ],
    techStack: ["Angular", "D3.js", "Node.js", "PostgreSQL", "TimescaleDB", "Redis", "Docker"],
    duration: "7 meses",
    team: "9 desenvolvedores",
    link: "#"
  },
  {
    id: 6,
    title: "Site Institucional Tech Company",
    client: "InnovaTech Corp",
    category: "web",
    year: 2025,
    technologies: ["react"],
    image: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
    icon: "🏢",
    shortDescription: "Website corporativo moderno com CMS headless e área de carreiras.",
    fullDescription: "Website institucional completo para empresa de tecnologia, incluindo apresentação de produtos, blog técnico, área de carreiras com integração de ATS, e portal de clientes.",
    challenge: "A InnovaTech estava crescendo rapidamente e precisava de um site escalável que suportasse conteúdo multilíngue, integração com ferramentas de marketing, e um sistema robusto de carreiras.",
    solution: "Desenvolvemos com Gatsby para performance máxima e SEO, Contentful como CMS headless para gestão de conteúdo multilíngue, integração com HubSpot para marketing automation, e API customizada para vagas com integração ao ATS Greenhouse.",
    results: [
      "Tempo de carregamento médio: 1.2s",
      "Suporte para 5 idiomas",
      "Aumento de 310% em candidaturas",
      "Blog técnico com 50.000+ visitas/mês",
      "Score 100/100 em acessibilidade"
    ],
    techStack: ["Gatsby", "Contentful", "Tailwind CSS", "HubSpot API", "Netlify"],
    duration: "4 meses",
    team: "5 desenvolvedores",
    link: "#"
  },
  {
    id: 7,
    title: "Plataforma de Cursos Online",
    client: "EduTech Academy",
    category: "system",
    year: 2026,
    technologies: ["react", "node"],
    image: "linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)",
    icon: "📚",
    shortDescription: "LMS completo com videoaulas, exercícios e certificados digitais.",
    fullDescription: "Learning Management System completo com streaming de vídeo, sistema de exercícios e provas, gamificação, certificados digitais, e marketplace de cursos.",
    challenge: "A EduTech queria criar uma plataforma que rivalizasse com grandes players como Udemy e Coursera, mas com foco no mercado brasileiro e recursos de interação ao vivo.",
    solution: "Desenvolvemos uma plataforma escalável usando React para interface rica, Node.js para backend, streaming de vídeo com AWS MediaConvert, live streaming com WebRTC, e blockchain para certificados verificáveis.",
    results: [
      "15.000+ alunos ativos",
      "500+ cursos publicados",
      "Taxa de conclusão de 68% (média mercado: 15%)",
      "Sistema de certificados blockchain",
      "Live classes com até 1000 participantes simultâneos"
    ],
    techStack: ["React", "Node.js", "MongoDB", "AWS MediaConvert", "WebRTC", "Stripe", "Ethereum"],
    duration: "8 meses",
    team: "10 desenvolvedores",
    link: "#"
  },
  {
    id: 8,
    title: "App de Gestão Financeira Pessoal",
    client: "MoneyWise Finance",
    category: "mobile",
    year: 2025,
    technologies: ["flutter", "node"],
    image: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
    icon: "💰",
    shortDescription: "App de finanças pessoais com IA para insights e recomendações.",
    fullDescription: "Aplicativo mobile de gestão financeira pessoal com categorização automática de gastos, metas de economia, integração bancária via Open Finance, e insights gerados por IA.",
    challenge: "O MoneyWise queria se diferenciar oferecendo insights realmente úteis e automação máxima, reduzindo o trabalho manual do usuário ao mínimo.",
    solution: "Criamos apps nativos com Flutter, integração Open Finance para sincronização automática de transações, machine learning para categorização inteligente de gastos, e chatbot com IA para consultas em linguagem natural.",
    results: [
      "100.000+ usuários ativos",
      "Integração com 50+ instituições financeiras",
      "Precisão de 94% na categorização automática",
      "Usuários economizaram em média R$ 380/mês",
      "Rating 4.7 estrelas nas stores"
    ],
    techStack: ["Flutter", "Node.js", "Python", "TensorFlow", "PostgreSQL", "Redis"],
    duration: "6 meses",
    team: "8 desenvolvedores",
    link: "#"
  },
  {
    id: 9,
    title: "Marketplace de Serviços Locais",
    client: "LocalPro Services",
    category: "web",
    year: 2026,
    technologies: ["vue", "node"],
    image: "linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)",
    icon: "🔧",
    shortDescription: "Plataforma para conectar prestadores de serviços locais a clientes.",
    fullDescription: "Marketplace completo conectando prestadores de serviços (encanadores, eletricistas, pintores, etc.) a clientes, com sistema de cotações, agendamento, pagamento integrado e avaliações.",
    challenge: "A LocalPro queria criar um marketplace confiável onde clientes pudessem encontrar profissionais qualificados rapidamente, e profissionais pudessem expandir sua clientela.",
    solution: "Desenvolvemos uma plataforma com Vue.js para interface responsiva, sistema de matching inteligente baseado em localização e disponibilidade, verificação de profissionais com documentação, sistema de cotações com chat em tempo real, e pagamento escrow para segurança.",
    results: [
      "5.000+ profissionais cadastrados",
      "50.000+ serviços realizados",
      "Tempo médio de matching: 15 minutos",
      "Taxa de satisfação: 92%",
      "Volume de transações: R$ 2.5 milhões/mês"
    ],
    techStack: ["Vue.js", "Node.js", "Socket.io", "PostgreSQL", "Stripe", "Google Maps API"],
    duration: "5 meses",
    team: "7 desenvolvedores",
    link: "#"
  },
  {
    id: 10,
    title: "Sistema de Reservas Hoteleiras",
    client: "StayEasy Hotels",
    category: "system",
    year: 2025,
    technologies: ["react", "laravel"],
    image: "linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%)",
    icon: "🏨",
    shortDescription: "Plataforma de gestão e reservas para rede de hotéis.",
    fullDescription: "Sistema completo de gestão hoteleira e reservas online, com channel manager, PMS (Property Management System), integração com OTAs, e CRM integrado.",
    challenge: "A StayEasy gerenciava 12 hotéis usando sistemas diferentes, causando overbooking, perda de reservas, e dificuldade na gestão de inventário.",
    solution: "Criamos uma plataforma unificada com React para interface administrativa e portal de reservas, Laravel para backend robusto, integração com principais OTAs (Booking, Expedia, Airbnb), sistema de preços dinâmicos, e automação de comunicação com hóspedes.",
    results: [
      "Centralização de 12 propriedades",
      "Zero casos de overbooking após implementação",
      "Aumento de 45% em reservas diretas",
      "Redução de 70% em trabalho manual",
      "Integração com 8 OTAs principais"
    ],
    techStack: ["React", "Laravel", "MySQL", "Redis", "Stripe", "Twilio"],
    duration: "7 meses",
    team: "9 desenvolvedores",
    link: "#"
  },
  {
    id: 11,
    title: "App de Meditação e Bem-Estar",
    client: "MindfulLife Wellness",
    category: "mobile",
    year: 2026,
    technologies: ["react-native", "node"],
    image: "linear-gradient(135deg, #d299c2 0%, #fef9d7 100%)",
    icon: "🧘",
    shortDescription: "Aplicativo de meditação guiada com conteúdo personalizado e tracking.",
    fullDescription: "App de saúde mental e meditação com sessões guiadas, música ambiente, journaling digital, tracking de humor, e recomendações personalizadas por IA.",
    challenge: "O MindfulLife queria criar uma experiência verdadeiramente personalizada, onde o app aprendesse com os hábitos do usuário e recomendasse conteúdo no momento certo.",
    solution: "Desenvolvemos com React Native para apps nativos, implementamos ML para análise de padrões de uso e recomendações, integração com Apple Health e Google Fit, notificações inteligentes baseadas em rotina, e áudio offline de alta qualidade.",
    results: [
      "500.000+ downloads",
      "Usuários meditam em média 18 minutos/dia",
      "90% de retenção após 30 dias",
      "Biblioteca com 1000+ meditações guiadas",
      "Integração com wearables para biofeedback"
    ],
    techStack: ["React Native", "Node.js", "MongoDB", "Python", "TensorFlow", "Firebase"],
    duration: "5 meses",
    team: "6 desenvolvedores",
    link: "#"
  },
  {
    id: 12,
    title: "Portal de Notícias Multimídia",
    client: "NewsStream Digital",
    category: "web",
    year: 2025,
    technologies: ["react", "node"],
    image: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)",
    icon: "📰",
    shortDescription: "Portal de notícias com vídeos, podcasts e paywall inteligente.",
    fullDescription: "Portal de notícias moderno com artigos, vídeos, podcasts, newsletter, sistema de assinatura com paywall medido, e app mobile complementar.",
    challenge: "A NewsStream precisava migrar do modelo tradicional para digital, implementar paywall sem perder audiência, e criar uma experiência multiplataforma coesa.",
    solution: "Desenvolvemos um portal com Next.js para SEO otimizado e performance, CMS headless personalizado para jornalistas, sistema de paywall inteligente que libera conteúdo baseado em comportamento, integração com sistema de pagamentos recorrentes, e apps mobile sincronizados.",
    results: [
      "80.000 assinantes pagos em 12 meses",
      "Tempo médio de sessão: 8 minutos",
      "Newsletter com 200.000 inscritos",
      "Conversão de visitantes em assinantes: 4.2%",
      "Apps mobile com 150.000+ downloads"
    ],
    techStack: ["Next.js", "Node.js", "PostgreSQL", "Redis", "Stripe", "React Native"],
    duration: "8 meses",
    team: "10 desenvolvedores",
    link: "#"
  },
  {
    id: 13,
    title: "Plataforma de Agendamento Multiservices",
    client: "BookNow Solutions",
    category: "system",
    year: 2026,
    technologies: ["vue", "laravel"],
    image: "linear-gradient(135deg, #fddb92 0%, #d1fdff 100%)",
    icon: "📅",
    shortDescription: "Sistema de agendamento para múltiplos tipos de serviços e profissionais.",
    fullDescription: "Plataforma white-label de agendamento online que pode ser customizada para qualquer tipo de negócio (salões, clínicas, academias, consultórios, etc.), com gestão de agenda, pagamentos, e marketing automation.",
    challenge: "A BookNow queria criar uma solução única que pudesse atender desde barbeiros individuais até redes de clínicas com centenas de profissionais.",
    solution: "Desenvolvemos uma arquitetura multi-tenant com Vue.js para interface customizável, Laravel para backend robusto, sistema de templates drag-and-drop para páginas de agendamento, integração com Google Calendar e Outlook, automação de lembretes por SMS/email, e sistema de fidelidade configurável.",
    results: [
      "2.000+ empresas usando a plataforma",
      "1 milhão+ agendamentos processados",
      "Taxa de no-show reduzida em 60%",
      "Automação economiza 15h/semana por empresa",
      "Integração com 20+ ferramentas de marketing"
    ],
    techStack: ["Vue.js", "Laravel", "MySQL", "Redis", "Twilio", "Stripe", "Mailgun"],
    duration: "6 meses",
    team: "8 desenvolvedores",
    link: "#"
  },
  {
    id: 14,
    title: "E-commerce de Moda Sustentável",
    client: "EcoFashion Store",
    category: "ecommerce",
    year: 2025,
    technologies: ["react", "node"],
    image: "linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)",
    icon: "👗",
    shortDescription: "Loja virtual focada em moda sustentável com rastreio de origem.",
    fullDescription: "E-commerce especializado em moda sustentável, com rastreamento de origem dos produtos via blockchain, calculadora de impacto ambiental, programa de trade-in, e marketplace para marcas parceiras.",
    challenge: "A EcoFashion queria provar a autenticidade de suas práticas sustentáveis de forma transparente e criar uma comunidade engajada em torno da marca.",
    solution: "Criamos uma loja com React para UX fluida, integração blockchain para rastreamento de produtos (da matéria-prima ao consumidor), sistema de pontos para programa de trade-in, calculadora de pegada de carbono salva, e comunidade com conteúdo educativo sobre sustentabilidade.",
    results: [
      "150% de crescimento em vendas ano-a-ano",
      "50.000+ peças rastreadas via blockchain",
      "Programa trade-in com 15.000 itens retornados",
      "Comunidade com 80.000 membros ativos",
      "NPS de 82 pontos"
    ],
    techStack: ["React", "Node.js", "MongoDB", "Ethereum", "Stripe", "AWS"],
    duration: "5 meses",
    team: "7 desenvolvedores",
    link: "#"
  },
  {
    id: 15,
    title: "App de Carona Corporativa",
    client: "RideShare Corp",
    category: "mobile",
    year: 2026,
    technologies: ["flutter", "node"],
    image: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    icon: "🚗",
    shortDescription: "Aplicativo de carona compartilhada para empresas.",
    fullDescription: "Solução de mobilidade corporativa que conecta funcionários da mesma empresa ou região para compartilhar caronas, com gestão de rotas, divisão automática de custos, e dashboard gerencial para RH.",
    challenge: "A RideShare Corp queria ajudar empresas a reduzirem custos com vale-transporte e estacionamento, enquanto promoviam sustentabilidade e networking entre funcionários.",
    solution: "Desenvolvemos apps com Flutter para iOS e Android, algoritmo de matching baseado em rotas e horários, sistema de divisão de custos automático, verificação de identidade corporativa, chat integrado, e dashboard web para empresas acompanharem estatísticas.",
    results: [
      "50 empresas parceiras",
      "20.000+ usuários ativos",
      "Economia média de R$ 400/mês por usuário",
      "Redução de 35% em veículos no estacionamento",
      "1.500 toneladas de CO2 evitadas"
    ],
    techStack: ["Flutter", "Node.js", "PostgreSQL", "Google Maps API", "Firebase", "Socket.io"],
    duration: "5 meses",
    team: "6 desenvolvedores",
    link: "#"
  },
  {
    id: 16,
    title: "Sistema de Gestão para Restaurantes",
    client: "FoodManager Pro",
    category: "system",
    year: 2025,
    technologies: ["angular", "laravel"],
    image: "linear-gradient(135deg, #ff6e7f 0%, #bfe9ff 100%)",
    icon: "🍽️",
    shortDescription: "ERP completo para gestão de restaurantes e deliveries.",
    fullDescription: "Sistema completo de gestão para restaurantes incluindo PDV, controle de estoque, gestão de fornecedores, cardápio digital com QR Code, integração com apps de delivery, e BI para análise de vendas.",
    challenge: "O FoodManager Pro estava atendendo restaurantes que usavam 5-7 sistemas diferentes, causando retrabalho, erros de estoque, e dificuldade em análise de dados.",
    solution: "Criamos um ERP all-in-one com Angular para interface administrativa, PDV otimizado para tablets, controle de estoque com alertas automáticos, integração com iFood/Rappi/Uber Eats, cardápio digital QR Code com gestão de disponibilidade em tempo real, e BI com insights sobre pratos mais vendidos, horários de pico, etc.",
    results: [
      "300+ restaurantes usando o sistema",
      "Redução de 80% em erros de pedido",
      "Controle de estoque com precisão de 98%",
      "Economia média de 25% em desperdício",
      "Integração com 5 apps de delivery"
    ],
    techStack: ["Angular", "Laravel", "MySQL", "Redis", "Docker", "BI Tools"],
    duration: "7 meses",
    team: "9 desenvolvedores",
    link: "#"
  },
  {
    id: 17,
    title: "Marketplace de Arte Digital (NFT)",
    client: "ArtVerse Gallery",
    category: "web",
    year: 2026,
    technologies: ["react", "node"],
    image: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
    icon: "🎭",
    shortDescription: "Marketplace de NFTs para artistas digitais.",
    fullDescription: "Plataforma completa para compra, venda e leilão de NFTs (arte digital), com carteira integrada, sistema de royalties automáticos para artistas, curadoria, e galeria virtual 3D.",
    challenge: "A ArtVerse queria democratizar o acesso ao mercado de NFTs, simplificando o processo para artistas e colecionadores não-técnicos.",
    solution: "Desenvolvemos uma plataforma com React para interface intuitiva, integração com Ethereum e Polygon, carteira custodial simplificada, sistema de minting facilitado com templates, contratos inteligentes para royalties perpétuos, galeria 3D com Three.js, e sistema de verificação de artistas.",
    results: [
      "15.000+ NFTs mintados",
      "5.000 artistas verificados",
      "Volume de transações: $5 milhões",
      "Taxa média de royalty para artistas: 12%",
      "Galeria 3D com 100.000+ visitas"
    ],
    techStack: ["React", "Node.js", "Solidity", "Ethereum", "IPFS", "Three.js", "Web3.js"],
    duration: "6 meses",
    team: "8 desenvolvedores",
    link: "#"
  },
  {
    id: 18,
    title: "App de Treinos Personalizados",
    client: "FitCoach Personal",
    category: "mobile",
    year: 2025,
    technologies: ["react-native", "node"],
    image: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    icon: "💪",
    shortDescription: "App de fitness com treinos personalizados por IA e acompanhamento.",
    fullDescription: "Aplicativo de treinos personalizados que usa IA para criar planos de exercícios adaptados ao usuário, com vídeos demonstrativos, tracking de progresso, integração com wearables, e coaching virtual.",
    challenge: "O FitCoach queria escalar o atendimento de personal trainers através de tecnologia, oferecendo personalização real sem perder a qualidade.",
    solution: "Criamos um app com React Native, algoritmo de ML que analisa objetivos, condição física e progresso para ajustar treinos, biblioteca com 2000+ exercícios em vídeo, integração com Apple Watch e dispositivos Android, chatbot para dúvidas sobre execução, e sistema de gamificação para engajamento.",
    results: [
      "300.000+ downloads",
      "Usuários treinam média de 4.5x por semana",
      "Taxa de retenção de 75% após 90 dias",
      "Integração com 15+ tipos de wearables",
      "Comunidade com 50.000 membros ativos"
    ],
    techStack: ["React Native", "Node.js", "Python", "TensorFlow", "MongoDB", "Firebase"],
    duration: "6 meses",
    team: "7 desenvolvedores",
    link: "#"
  },
  {
    id: 19,
    title: "Plataforma de Telemedicina",
    client: "HealthConnect Online",
    category: "system",
    year: 2026,
    technologies: ["vue", "node"],
    image: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
    icon: "⚕️",
    shortDescription: "Sistema completo de telemedicina com videoconferência e prontuário.",
    fullDescription: "Plataforma de telemedicina com agendamento online, videoconferência médico-paciente, prontuário eletrônico, prescrição digital, integração com farmácias, e sistema de pagamento.",
    challenge: "A HealthConnect precisava de uma solução que atendesse rigorosas normas de privacidade (LGPD, HIPAA), oferecesse qualidade de vídeo estável mesmo em conexões ruins, e se integrasse com sistemas legados de clínicas.",
    solution: "Desenvolvemos com Vue.js para interface responsiva, WebRTC customizado com fallbacks para conexões instáveis, criptografia ponta-a-ponta para vídeo e dados, prontuário eletrônico com assinatura digital, integração com APIs de farmácias para envio de receitas, e compliance total com LGPD.",
    results: [
      "100.000+ consultas realizadas",
      "500+ médicos credenciados",
      "Tempo médio de consulta: 22 minutos",
      "Qualidade de vídeo estável em 98% das consultas",
      "Integração com 150+ farmácias"
    ],
    techStack: ["Vue.js", "Node.js", "WebRTC", "PostgreSQL", "Redis", "Docker"],
    duration: "8 meses",
    team: "10 desenvolvedores",
    link: "#"
  },
  {
    id: 20,
    title: "E-commerce de Produtos Artesanais",
    client: "HandMade Market",
    category: "ecommerce",
    year: 2025,
    technologies: ["react", "laravel"],
    image: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
    icon: "🎨",
    shortDescription: "Marketplace para artesãos venderem produtos feitos à mão.",
    fullDescription: "Marketplace conectando artesãos locais a consumidores interessados em produtos únicos e feitos à mão, com sistema de vendas, gestão de inventário, histórias dos artesãos, e programa de certificação de autenticidade.",
    challenge: "O HandMade Market queria criar confiança em produtos artesanais, combater falsificações, e dar visibilidade a pequenos artesãos.",
    solution: "Desenvolvemos um marketplace com React, sistema de verificação de artesãos com documentação, storytelling rico com fotos e vídeos do processo de criação, selo de autenticidade digital, sistema de reviews verificados (compra confirmada), ferramentas de gestão simplificadas para artesãos não-técnicos, e logística integrada.",
    results: [
      "10.000+ artesãos cadastrados",
      "500.000+ produtos únicos",
      "GMV: R$ 15 milhões/ano",
      "Taxa de satisfação: 96%",
      "Programa de certificação com 8.000 artesãos verificados"
    ],
    techStack: ["React", "Laravel", "MySQL", "Redis", "Stripe", "AWS S3"],
    duration: "5 meses",
    team: "7 desenvolvedores",
    link: "#"
  },
  {
    id: 21,
    title: "Sistema de CRM B2B Avançado",
    client: "SalesPro Enterprise",
    category: "system",
    year: 2026,
    technologies: ["angular", "node"],
    image: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    icon: "📈",
    shortDescription: "CRM empresarial com automação de vendas e previsão por IA.",
    fullDescription: "Sistema de CRM completo para vendas B2B com gestão de pipeline, automação de follow-ups, previsão de vendas por IA, integração com email e telefone, e dashboards executivos.",
    challenge: "A SalesPro queria criar um CRM que realmente aumentasse produtividade de vendedores, ao invés de apenas gerar trabalho administrativo.",
    solution: "Desenvolvemos com Angular para interface rica, automação de captura de emails e ligações, IA que sugere próximas ações baseado em padrões de sucesso, integração com Gmail/Outlook/Calendário, sistema de scoring de leads automático, e analytics preditivo para forecast de vendas.",
    results: [
      "500+ empresas usando",
      "Aumento médio de 45% em conversões",
      "Redução de 60% em tempo administrativo",
      "Precisão de 87% em previsão de vendas",
      "Integração com 30+ ferramentas de vendas"
    ],
    techStack: ["Angular", "Node.js", "PostgreSQL", "Python", "TensorFlow", "Redis"],
    duration: "7 meses",
    team: "9 desenvolvedores",
    link: "#"
  },
  {
    id: 22,
    title: "App de Receitas e Planejamento de Refeições",
    client: "CookSmart Family",
    category: "mobile",
    year: 2025,
    technologies: ["flutter", "node"],
    image: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
    icon: "🍳",
    shortDescription: "App de receitas com planejamento semanal e lista de compras automática.",
    fullDescription: "Aplicativo de receitas com recomendações personalizadas baseadas em preferências e restrições alimentares, planejamento semanal de refeições, geração automática de lista de compras, e modo passo-a-passo para cozinhar.",
    challenge: "O CookSmart queria simplificar a vida de famílias ocupadas, reduzindo o estresse de decidir 'o que fazer para jantar' todos os dias.",
    solution: "Criamos app com Flutter, ML para recomendações baseadas em histórico e preferências, banco com 10.000+ receitas, planejamento drag-and-drop de refeições semanais, lista de compras inteligente que agrupa ingredientes por seção do mercado, modo hands-free com comandos de voz para cozinhar, e integração com serviços de delivery de supermercado.",
    results: [
      "750.000+ downloads",
      "Usuários planejam média de 5.2 refeições/semana",
      "Redução de 40% em desperdício de alimentos",
      "10.000+ receitas com foto passo-a-passo",
      "Integração com 3 serviços de delivery"
    ],
    techStack: ["Flutter", "Node.js", "MongoDB", "Python", "TensorFlow", "Firebase"],
    duration: "5 meses",
    team: "6 desenvolvedores",
    link: "#"
  },
  {
    id: 23,
    title: "Portal de Imóveis Inteligente",
    client: "SmartHome Realty",
    category: "web",
    year: 2026,
    technologies: ["react", "node"],
    image: "linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%)",
    icon: "🏠",
    shortDescription: "Portal imobiliário com tours virtuais 360° e matching por IA.",
    fullDescription: "Plataforma de compra e aluguel de imóveis com busca avançada, tours virtuais 360°, matching inteligente por IA, calculadora de financiamento, e agendamento de visitas integrado.",
    challenge: "A SmartHome queria oferecer uma experiência superior que reduzisse visitas desnecessárias e ajudasse compradores a encontrarem seu imóvel ideal mais rapidamente.",
    solution: "Desenvolvemos portal com React e Next.js para SEO, integração com câmeras 360° para tours virtuais imersivos, algoritmo de ML que aprende preferências do usuário e recomenda imóveis, simulador de financiamento em tempo real com múltiplos bancos, mapa interativo com pontos de interesse, e chatbot para agendamento de visitas.",
    results: [
      "50.000+ imóveis cadastrados",
      "Tours 360° em 80% dos imóveis",
      "Redução de 55% em visitas presenciais",
      "Tempo médio para encontrar imóvel: 18 dias (vs 45 dias média mercado)",
      "15.000+ negócios fechados via plataforma"
    ],
    techStack: ["Next.js", "Node.js", "PostgreSQL", "Three.js", "Python", "TensorFlow"],
    duration: "6 meses",
    team: "8 desenvolvedores",
    link: "#"
  },
  {
    id: 24,
    title: "Sistema de Gestão para Academias",
    client: "GymFlow Manager",
    category: "system",
    year: 2025,
    technologies: ["vue", "laravel"],
    image: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    icon: "🏋️",
    shortDescription: "ERP completo para gestão de academias com app do aluno.",
    fullDescription: "Sistema completo de gestão para academias incluindo controle de acesso biométrico, gestão de planos e pagamentos, agendamento de aulas, app do aluno com treinos, e dashboards de retenção.",
    challenge: "O GymFlow atendia academias que lutavam com alta taxa de churn (cancelamento) e dificuldade em engajar alunos fora do horário de treino.",
    solution: "Criamos um sistema com Vue.js para web admin, integração com catracas biométricas, gestão automática de cobranças recorrentes, app mobile para alunos com treinos personalizados e agendamento de aulas, gamificação com desafios e ranking, sistema de NPS automático, e analytics preditivo de churn.",
    results: [
      "200+ academias usando",
      "Redução de 35% na taxa de churn",
      "Aumento de 50% em engajamento",
      "Automação de 90% das cobranças",
      "App com 100.000+ alunos ativos"
    ],
    techStack: ["Vue.js", "Laravel", "MySQL", "React Native", "Stripe", "Redis"],
    duration: "7 meses",
    team: "9 desenvolvedores",
    link: "#"
  }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = projectsData;
}
